import 'package:flutter/material.dart';
import 'package:onboarding_pro_multi/step_model.dart';
import 'package:onboarding_pro_multi/strings.dart';

const stepsList = [
  SingleStep(
    label: creativeTime,
    foregroundImage: '0-f.png',
    backgroundImage: '0-b.png',
    backgroundGradientAlignment: Alignment(0, -0.2),
    decorImages: [
      Decor(image: 'cross.png', alignment: Alignment(-0.75, 0.35)),
      Decor(image: 'ticket.png', alignment: Alignment(-0.9, 0.25)),
      Decor(image: 'star-5-blue.png', alignment: Alignment(-0.75, 0.05)),
      Decor(image: 'bubbles.png', alignment: Alignment(-0.85, -0.05)),
      Decor(image: 'cloud-small.png', alignment: Alignment(-0.8, -0.45)),
      Decor(image: 'dots-medium.png', alignment: Alignment(-0.7, -0.35)),
      Decor(image: 'cloud-big.png', alignment: Alignment(0.45, -0.9)),
      Decor(image: 'cloud-small.png', alignment: Alignment(0.9, -0.7)),
      Decor(image: 'movie.png', alignment: Alignment(0.5, -0.6)),
      Decor(image: 'mic.png', alignment: Alignment(0.65, -0.4)),
      Decor(image: 'dots-big.png', alignment: Alignment(0.85, 0.3)),
      Decor(image: 'party.png', alignment: Alignment(0.5, 0.1)),
    ],
  ),
  SingleStep(
    label: events,
    foregroundImage: '1-f.png',
    backgroundImage: '1-b.png',
    backgroundGradientAlignment: Alignment(0.25, 0.2),
    decorImages: [
      Decor(image: 'dots-small.png', alignment: Alignment(-0.7, 0.9)),
      Decor(image: 'star-6-white.png', alignment: Alignment(-0.5, 0.9)),
      Decor(image: 'star-5-white.png', alignment: Alignment(-0.4, 0.45)),
      Decor(image: 'bubbles.png', alignment: Alignment(-0.5, 0.4)),
      Decor(image: 'dots-big.png', alignment: Alignment(-0.6, -0.8)),
      Decor(image: 'location.png', alignment: Alignment(-0.35, -0.6)),
      Decor(image: 'party.png', alignment: Alignment(-0.55, -0.4)),
      Decor(image: 'book.png', alignment: Alignment(-0.35, -0.25)),
      Decor(image: 'spark-1.png', alignment: Alignment(0, -0.8)),
      Decor(image: 'spark-2.png', alignment: Alignment(0.5, -1)),
      Decor(image: 'star-4-white.png', alignment: Alignment(0, -1)),
      Decor(image: 'star-4-white.png', alignment: Alignment(-0.05, -0.4)),
      Decor(image: 'star-4-white.png', alignment: Alignment(0.2, -0.5)),
    ],
  ),
  SingleStep(
    label: newPlaces,
    foregroundImage: '2-f.png',
    backgroundImage: '2-b.png',
    backgroundGradientAlignment: Alignment.center,
    decorImages: [
      Decor(image: 'location.png', alignment: Alignment(-0.85, -0.2)),
      Decor(image: 'star-6-green.png', alignment: Alignment(-0.9, -0.5)),
      Decor(image: 'cloud-small.png', alignment: Alignment(-0.85, -1)),
      // Decor(image: 'moon.png', alignment: Alignment(0, -1)),
      // Decor(image: 'dots-small.png', alignment: Alignment(-0.2, -0.9)),
      Decor(image: 'cloud-big.png', alignment: Alignment(0.85, -1)),
      Decor(image: 'dots-small.png', alignment: Alignment(0.75, -0.8)),
    ],
  ),
  SingleStep(
    label: reminders,
    foregroundImage: '3-f.png',
    backgroundImage: '3-b.png',
    backgroundGradientAlignment: Alignment(0.25, 0),
    decorImages: [
      Decor(image: 'star-6-orange.png', alignment: Alignment(-0.85, 0.1)),
      Decor(image: 'dots-small.png', alignment: Alignment(-0.85, -0.3)),
      Decor(image: 'cloud-small.png', alignment: Alignment(-0.75, -0.95)),
      Decor(image: 'cloud-big.png', alignment: Alignment(0.9, -1)),
      Decor(image: 'dots-small.png', alignment: Alignment(0.9, 0.6)),
    ],
  ),
  SingleStep(
    label: upToDate,
    foregroundImage: '4-f.png',
    backgroundImage: '4-b.png',
    backgroundGradientAlignment: Alignment.center,
    decorImages: [
      Decor(image: 'star-6-green.png', alignment: Alignment(-0.65, -0.4)),
      Decor(image: 'documents.png', alignment: Alignment(-0.45, -0.4)),
      Decor(image: 'direction.png', alignment: Alignment(-0.2, -0.6)),
      Decor(image: 'heart.png', alignment: Alignment(0.1, -0.45)),
      Decor(image: 'dots-small.png', alignment: Alignment(0.85, -0.1)),
      Decor(image: 'dots-big.png', alignment: Alignment(0.65, -0.9)),
      Decor(image: 'cloud-big.png', alignment: Alignment(0.85, -0.8)),
      Decor(image: 'cloud-small.png', alignment: Alignment(0.3, -1)),
      Decor(image: 'star-4-orange.png', alignment: Alignment(0.9, -1)),
    ],
  ),
  SingleStep(
    label: rhythm,
    foregroundImage: '5-f.png',
    backgroundImage: '5-b.png',
    backgroundGradientAlignment: Alignment(0.25, 0),
    decorImages: [
      Decor(image: 'rocket.png', alignment: Alignment(-0.8, 1)),
      Decor(image: 'dots-big.png', alignment: Alignment(-0.85, 1)),
      Decor(image: 'round-rect.png', alignment: Alignment(-0.85, 0.4)),
      Decor(image: 'dots-medium.png', alignment: Alignment(-0.3, -0.8)),
      Decor(image: 'cloud-small.png', alignment: Alignment(-0.2, -0.6)),
      Decor(image: 'cloud-big.png', alignment: Alignment(-0.8, -1)),
      Decor(image: 'bubbles.png', alignment: Alignment(0.65, -0.5)),
      Decor(image: 'star-5-white.png', alignment: Alignment(0.8, -0.4)),
    ],
  ),
];
