const creativeTime = 'Spędzaj czas\n<em>kreatywnie</em>!';
const events = '<em>Bierz udział</em>\nw wydarzeniach!';
const newPlaces = 'Poznawaj\nnieodkryte <em>szlaki</em>!';
const reminders = 'Ustawiaj\n<em>przypomnienia</em>!';
const upToDate = 'Bądź <em>na bieżąco</em>!';
const rhythm = 'Złap <em>swój rytm!</em>';
const buttonSkip = 'Pomiń';
const buttonForward = 'Dalej';
const buttonStart = 'Zaczynamy!';
