const creativeTime = 'Spędzaj czas <em>kreatywnie</em>!';
const events = '<em>Bierz udział</em> w wydarzeniach!';
const newPlaces = 'Poznawaj nieodkryte <em>szlaki</em>!';
const reminders = 'Ustawiaj <em>przypomnienia</em>!';
const upToDate = 'Bądź <em>na bieżąco</em>!';
const rhythm = 'Złap <em>swój rytm!</em>';
const buttonSkip = 'Pomiń';
const buttonForward = 'Dalej';
const buttonStart = 'Zaczynamy!';
